### ISSUE TITLE
Update to new testthat convention

### ISSUE THREAD

**Issue by wibeasley** [rdotnet/rClr#20]
Would you like me to move the tests to the new directory that [testthat recommends](https://github.com/hadley/testthat)?

I see your [test-all.R](https://github.com/jmp75/rClr/blob/master/tests/test-all.R) file is more complicated than most, but I'm willing to try if it would be helpful to you.  Because this package supports [rsqlserver](https://github.com/agstudy/rsqlserver), it saves me a lot of time.

``` r
> testthat::test_package('rClr')
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.18444

rClr essentials : ...............................................................................................................................................................................................
Date and times : .....................................................................................................................................

DONE 
Warning message:
Placing tests in `inst/tests/` is deprecated. Please use `tests/testthat/` instead 
```

**Comment by jmp75** [comment]
Started on this a month ago, currently on the testing and/or devel branches.

**Comment by wibeasley** [comment]
Cool.  Tell me if you'd like me to help with anything.  I've done this for a few of my packages, and I'm happy to contribute to this one, if it would be useful to you.
